 # This file is automatically generated by fillnops.s
 # DO NOT EDIT THIS FILE
 # The purpose of this file is to fill in the space between
 # the end of ginit.s and the beginning of gsetup.s which
 # will later be overlayed by gclip.s and gflight.s
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
