d2 1
a2 1
	gcc -Wall -o bsl main.o integer_math.o poly_math.o elliptic_math.o algorithms.o
d5 1
a5 1
	gcc -Wall -c integer_math.c
d8 1
a8 1
	gcc -Wall -c poly_math.c
d11 1
a11 1
	gcc -Wall -c elliptic_math.c
d14 1
a14 1
	gcc -Wall -c algorithms.c
