;mushariusagi		equ	+(* - MSADRS) / 3 + 1
;0
	db	084h
	dw	hariusagi1
	db	005h
	dw	hariusagi2
	db	007h
	dw	hariusagi3

;mushariusagi@		equ	+(* - MSADRS) / 3 + 1
;1
	db	084h
	dw	hariusagi@1
	db	005h
	dw	hariusagi@2
	db	007h
	dw	hariusagi@3

;musyaddon		equ	+(* - MSADRS) / 3 + 1
;2
	db	084h
	dw	yaddon1
	db	005h
	dw	yaddon2
	db	007h
	dw	yaddon3

;musgarura	equ	+(* - MSADRS) / 3 + 1
;3
	db	084h
	dw	garura1
	db	005h
	dw	garura2
	db	007h
	dw	garura3

;muscyhorne	equ	+(* - MSADRS) / 3 + 1
;4
	db	084h
	dw	cyhorne1
	db	005h
	dw	cyhorne2
	db	007h
	dw	cyhorne3

;musbettobeter		equ	+(* - MSADRS) / 3 + 1
;5
	db	084h
	dw	bettobeter1
	db	005h
	dw	bettobeter2
	db	007h
	dw	bettobeter3

;musbiriridama		equ	+(* - MSADRS) / 3 + 1
;6
	db	084h
	dw	biriridama1
	db	005h
	dw	biriridama2
	db	007h
	dw	biriridama3

;musgengar		equ	+(* - MSADRS) / 3 + 1
;7
	db	084h
	dw	gengar1
	db	005h
	dw	gengar2
	db	007h
	dw	gengar3

;musfushigiso	equ	+(* - MSADRS) / 3 + 1
;8
	db	084h
	dw	fushigiso1
	db	005h
	dw	fushigiso2
	db	007h
	dw	fushigiso3

;musmycor	equ	+(* - MSADRS) / 3 + 1
;9
	db	084h
	dw	mycor1
	db	005h
	dw	mycor2
	db	007h
	dw	mycor3

;musmycor@	equ	+(* - MSADRS) / 3 + 1
;10
	db	084h
	dw	mycor@1
	db	005h
	dw	mycor@2
	db	007h
	dw	mycor@3

;mustamatama		equ	+(* - MSADRS) / 3 + 1
;11
	db	084h
	dw	tamatama1
	db	005h
	dw	tamatama2
	db	007h
	dw	tamatama3

;musbeloringa		equ	+(* - MSADRS) / 3 + 1
;12
	db	084h
	dw	beloringa1
	db	005h
	dw	beloringa2
	db	007h
	dw	beloringa3

;musnasshii		equ	+(* - MSADRS) / 3 + 1
;13
	db	084h
	dw	nasshii1
	db	005h
	dw	nasshii2
	db	007h
	dw	nasshii3

;muspip		equ	+(* - MSADRS) / 3 + 1
;14
	db	084h
	dw	pip1
	db	005h
	dw	pip2
	db	007h
	dw	pip3

;musgyace	equ	+(* - MSADRS) / 3 + 1
;15
	db	084h
	dw	gyace1
	db	005h
	dw	gyace2
	db	007h
	dw	gyace3

;musomom		equ	+(* - MSADRS) / 3 + 1
;16
	db	084h
	dw	omom1
	db	005h
	dw	omom2
	db	007h
	dw	omom3

;musgagarth	equ	+(* - MSADRS) / 3 + 1
;17
	db	084h
	dw	gagarth1
	db	005h
	dw	gagarth2
	db	007h
	dw	gagarth3

;musmonjara	equ	+(* - MSADRS) / 3 + 1
;18
	db	084h
	dw	monjara1
	db	005h
	dw	monjara2
	db	007h
	dw	monjara3

;musomega	equ	+(* - MSADRS) / 3 + 1
;19
	db	084h
	dw	omega1
	db	005h
	dw	omega2
	db	007h
	dw	omega3

;muscaiross	equ	+(* - MSADRS) / 3 + 1
;20
	db	084h
	dw	caiross1
	db	005h
	dw	caiross2
	db	007h
	dw	caiross3

;muswing		equ	+(* - MSADRS) / 3 + 1
;21
	db	084h
	dw	wing1
	db	005h
	dw	wing2
	db	007h
	dw	wing3

;musstrike		equ	+(* - MSADRS) / 3 + 1
;22
	db	084h
	dw	strike1
	db	005h
	dw	strike2
	db	007h
	dw	strike3

;musgyaradoss		equ	+(* - MSADRS) / 3 + 1
;23
	db	084h
	dw	gyaradoss1
	db	005h
	dw	gyaradoss2
	db	007h
	dw	gyaradoss3

;musshellder	equ	+(* - MSADRS) / 3 + 1
;24
	db	084h
	dw	shellder1
	db	005h
	dw	shellder2
	db	007h
	dw	shellder3

;muskarakara	equ	+(* - MSADRS) / 3 + 1
;25
	db	084h
	dw	karakara1
	db	005h
	dw	karakara2
	db	007h
	dw	karakara3

;musambler	equ	+(* - MSADRS) / 3 + 1
;26
	db	084h
	dw	ambler1
	db	005h
	dw	ambler2
	db	007h
	dw	ambler3

;musrapruth	equ	+(* - MSADRS) / 3 + 1
;27
	db	084h
	dw	rapruth1
	db	005h
	dw	rapruth2
	db	007h
	dw	rapruth3

;musgouth	equ	+(* - MSADRS) / 3 + 1
;28
	db	084h
	dw	gouth1
	db	005h
	dw	gouth2
	db	007h
	dw	gouth3

;muskarabatheo	equ	+(* - MSADRS) / 3 + 1
;29
	db	084h
	dw	karabatheo1
	db	005h
	dw	karabatheo2
	db	007h
	dw	karabatheo3

;musmimi		equ	+(* - MSADRS) / 3 + 1
;30
	db	084h
	dw	mimi1
	db	005h
	dw	mimi2
	db	007h
	dw	mimi3

;musyaddohogera	equ	+(* - MSADRS) / 3 + 1
;31
	db	084h
	dw	yaddohogera1
	db	005h
	dw	yaddohogera2
	db	007h
	dw	yaddohogera3

;mus34	equ	+(* - MSADRS) / 3 + 1
	db	084h
	dw	No34_1
	db	005h
	dw	No34_2
	db	007h
	dw	No34_3

;mus36	equ	+(* - MSADRS) / 3 + 1
	db	084h
	dw	No36_1
	db	005h
	dw	No36_2
	db	007h
	dw	No36_3

;musdog	equ	+(* - MSADRS) / 3 + 1
	db	084h
	dw	dog1
	db	005h
	dw	dog2
	db	007h
	dw	dog3




;muskingthaurus	equ	+(* - MSADRS) / 3 + 1
	db	084h
	dw	kingthaurus1
	db	005h
	dw	kingthaurus2
	db	007h
	dw	kingthaurus3

;mussutegon	equ	+(* - MSADRS) / 3 + 1
	db	084h
	dw	sutegon1
	db	005h
	dw	sutegon2
	db	007h
	dw	sutegon3

;museleking	equ	+(* - MSADRS) / 3 + 1
	db	084h
	dw	eleking1
	db	005h
	dw	eleking2
	db	007h
	dw	eleking3



