
;---------------------------------------------------------------;
;===============================================================;
;								;
;	      MONSTER VOICE Sound Effects Number EQU		;
;								;
;===============================================================;
;---------------------------------------------------------------;
NO_VOICE	equ	0ffh

MVC01	equ	00	; mushariusagi
MVC02	equ	01	; mushariusagi@
MVC03	equ	02	; musyaddon
MVC04	equ	03	; musgarura
MVC05	equ	04	; muscyhorne
MVC06	equ	05	; musbettobeter
MVC07	equ	06	; musbiriridama
MVC08	equ	07	; musgengar
MVC09	equ	08	; musfushigiso
MVC10	equ	09	; musmycor
MVC11	equ	10	; musmycor@
MVC12	equ	11	; mustamatama
MVC13	equ	12	; musbeloringa
MVC14	equ	13	; musnasshii
MVC15	equ	14	; muspip
MVC16	equ	15	; musgyace
MVC17	equ	16	; musomom
MVC18	equ	17	; musgagarth
MVC19	equ	18	; musmonjara
MVC20	equ	19	; musomega
MVC21	equ	20	; muscaiross
MVC22	equ	21	; muswing
MVC23	equ	22	; musstrike
MVC24	equ	23	; musgyaradoss
MVC25	equ	24	; musshellder
MVC26	equ	25	; muskarakara
MVC27	equ	26	; musambler
MVC28	equ	27	; musrapruth
MVC29	equ	28	; musgouth
MVC30	equ	29	; muskarabatheo
MVC31	equ	30	; musmimi
MVC32	equ	31	; musyaddohogera
;MVC33	equ	32	; mus32
MVC34	equ	32	; mus34
MVC35	equ	33	; mus36
MVC36	equ	34	; musdog
MVC37	equ	35	; muskingthaurus
MVC38	equ	36	; mussutegon
MVC39	equ	37	; museleking

