/**
* @file trlEmuMenuDataAction.h
* @author zhfang
* @date 2011.07.02
* @brief trlEmuMenu
*/
#pragma once
#include "trlEmuMenu.h"
#include "trlEmuMenuData.h"

extern trlEmuMenuAction cgbvcm_action_init;
extern trlEmuMenuAction cgbvcm_action_mainopen;
extern trlEmuMenuAction cgbvcm_action_mainclose;
extern trlEmuMenuAction cgbvcm_action_mainclosex;

extern trlEmuMenuAction cgbvcm_action_saveopen;
extern trlEmuMenuAction cgbvcm_action_saveback;
extern trlEmuMenuAction cgbvcm_action_saveing;
extern trlEmuMenuAction cgbvcm_action_saveokopen;
extern trlEmuMenuAction cgbvcm_action_saveokclose;

extern trlEmuMenuAction cgbvcm_action_loadopen;
extern trlEmuMenuAction cgbvcm_action_loadback;
extern trlEmuMenuAction cgbvcm_action_loading;
extern trlEmuMenuAction cgbvcm_action_loadokopen;
extern trlEmuMenuAction cgbvcm_action_loadokclose;

extern trlEmuMenuAction cgbvcm_action_resetopen;
extern trlEmuMenuAction cgbvcm_action_resetback;
extern trlEmuMenuAction cgbvcm_action_reseting;
extern trlEmuMenuAction cgbvcm_action_resetingclose;

extern trlEmuMenuAction cgbvcm_action_nmainopen0;
extern trlEmuMenuAction cgbvcm_action_nmainopen1;
extern trlEmuMenuAction cgbvcm_action_nmainclose;
extern trlEmuMenuAction cgbvcm_action_nmainclosex;

extern trlEmuMenuAction cgbvcm_action_nresetopen;
extern trlEmuMenuAction cgbvcm_action_nresetback;
extern trlEmuMenuAction cgbvcm_action_nreseting;
extern trlEmuMenuAction cgbvcm_action_nresetingclose;

extern trlEmuMenuAction cgbvcm_action_modechange_w00_open;
extern trlEmuMenuAction cgbvcm_action_modechange_w00_back;
extern trlEmuMenuAction cgbvcm_action_modechange_w01_open;
extern trlEmuMenuAction cgbvcm_action_modechange_w01_back;
extern trlEmuMenuAction cgbvcm_action_modechange_w01_close;
extern trlEmuMenuAction cgbvcm_action_modechange_ntoa0;
extern trlEmuMenuAction cgbvcm_action_modechange_ntoa1;
extern trlEmuMenuAction cgbvcm_action_modechange_aton0;
extern trlEmuMenuAction cgbvcm_action_modechange_aton1;

extern trlEmuMenuAction errvcm_action_notformatwait_open;
extern trlEmuMenuAction errvcm_action_notformatwait_close;
extern trlEmuMenuAction errvcm_action_badformatok_open;
extern trlEmuMenuAction errvcm_action_badformatok_beginwait;
extern trlEmuMenuAction errvcm_action_badformatok_closewait_done;
extern trlEmuMenuAction errvcm_action_badformatdone_close;
extern trlEmuMenuAction errvcm_action_vfailedok_open;
extern trlEmuMenuAction errvcm_action_vfailedok_beginwait;
extern trlEmuMenuAction errvcm_action_vfailedok_closewait_done;
extern trlEmuMenuAction errvcm_action_vfaileddone_close;
extern trlEmuMenuAction errvcm_action_opdeniedwait_open;

extern trlEmuMenuAction cgbvcm_action_firsttime_w00_open;
extern trlEmuMenuAction cgbvcm_action_firsttime_w00_2_w01;
extern trlEmuMenuAction cgbvcm_action_firsttime_w00_2_w02;
extern trlEmuMenuAction cgbvcm_action_firsttime_w02_2_w00;
extern trlEmuMenuAction cgbvcm_action_firsttime_w02_2_w03;
extern trlEmuMenuAction cgbvcm_action_firsttime_w03_2_w02;
extern trlEmuMenuAction cgbvcm_action_firsttime_w03_2_w01;
extern trlEmuMenuAction cgbvcm_action_firsttime_w01_2_nmain;
extern trlEmuMenuAction cgbvcm_action_firsttime_w01_2_modechangentoa0;

extern trlEmuMenuAction cgbvcm_action_mainfadein;
extern trlEmuMenuAction cgbvcm_action_nmainfadein;
extern trlEmuMenuAction cgbvcm_action_mainfadeout;
extern trlEmuMenuAction cgbvcm_action_nmainfadeout;

extern trlEmuMenuAction cgbvcm_action_dlpbegin2dlpbeginback;
extern trlEmuMenuAction cgbvcm_action_dlpbeginback2dlpbegin;
extern trlEmuMenuAction cgbvcm_action_dlpbeginback2backmain;
extern trlEmuMenuAction cgbvcm_action_dlpbeginback2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_dlpbegin2dlpconn;
extern trlEmuMenuAction cgbvcm_action_dlpbegin2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_dlpconn2dlpconnback;
extern trlEmuMenuAction cgbvcm_action_dlpconn2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_dlpconnback2dlpconn;
extern trlEmuMenuAction cgbvcm_action_dlpconnback2backmain;
extern trlEmuMenuAction cgbvcm_action_dlpconnback2dlpdlperror;

extern trlEmuMenuAction cgbvcm_action_dlpconn2dlp;
extern trlEmuMenuAction cgbvcm_action_dlp2dlpnetinit;
extern trlEmuMenuAction cgbvcm_action_dlp2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_dlp2dlpback;
extern trlEmuMenuAction cgbvcm_action_dlpback2dlp;
extern trlEmuMenuAction cgbvcm_action_dlpback2backmain;
extern trlEmuMenuAction cgbvcm_action_dlpback2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_dlpnetinit2dlps;
extern trlEmuMenuAction cgbvcm_action_dlpnetinit2dlpnetinitback;
extern trlEmuMenuAction cgbvcm_action_dlpnetinitback2dlpnetinit;
extern trlEmuMenuAction cgbvcm_action_dlpnetinitback2backmain;
extern trlEmuMenuAction cgbvcm_action_dlpnetinitback2dlps;
extern trlEmuMenuAction cgbvcm_action_dlps2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_dlps2dlpwait;
extern trlEmuMenuAction cgbvcm_action_dlpwait2dlpchilderror;
extern trlEmuMenuAction cgbvcm_action_dlpwait2dlpwaitback;
extern trlEmuMenuAction cgbvcm_action_dlpwaitback2dlpwait;
extern trlEmuMenuAction cgbvcm_action_dlpwaitback2dlpchilderror;
extern trlEmuMenuAction cgbvcm_action_dlpwaitback2dlpchildendwait;
extern trlEmuMenuAction cgbvcm_action_dlps2dlpok;
extern trlEmuMenuAction cgbvcm_action_dlps2dlpstandby;
extern trlEmuMenuAction cgbvcm_action_dlps2dlpnstandby;
extern trlEmuMenuAction cgbvcm_action_dlpok2dlpstandby;
extern trlEmuMenuAction cgbvcm_action_dlpok2dlpnstandby;
extern trlEmuMenuAction cgbvcm_action_dlpok2dlperror;
extern trlEmuMenuAction cgbvcm_action_dlpwait2dlpchildstandby;

extern trlEmuMenuAction cgbvcm_action_dlpmain_open;
extern trlEmuMenuAction cgbvcm_action_dlpnmain_open;

extern trlEmuMenuAction cgbvcm_action_dlpstandby2dlperror;
extern trlEmuMenuAction cgbvcm_action_dlpstandby2dlpnerror;
extern trlEmuMenuAction cgbvcm_action_dlpmain2dlperror;
extern trlEmuMenuAction cgbvcm_action_dlpnmain2dlperror;

extern trlEmuMenuAction cgbvcm_action_dlpchildmain_open;
extern trlEmuMenuAction cgbvcm_action_dlpmain_close;
extern trlEmuMenuAction cgbvcm_action_dlpnmain_close;
extern trlEmuMenuAction cgbvcm_action_dlpchildmain_close;

extern trlEmuMenuAction cgbvcm_action_dlperrorok_open;
extern trlEmuMenuAction cgbvcm_action_dlpnerrorok_open;

extern trlEmuMenuAction cgbvcm_action_dlpothermenu_open;
extern trlEmuMenuAction cgbvcm_action_dlpnothermenu_open;
extern trlEmuMenuAction cgbvcm_action_dlpothermenu_close;
extern trlEmuMenuAction cgbvcm_action_dlpnothermenu_close;
extern trlEmuMenuAction cgbvcm_action_dlpothermenu2dlperror;

extern trlEmuMenuAction cgbvcm_action_dlpchildothermenu_open;
extern trlEmuMenuAction cgbvcm_action_dlpchilderrors_open;
extern trlEmuMenuAction cgbvcm_action_dlpchildothermenu_close;
extern trlEmuMenuAction cgbvcm_action_dlpchildothermenu2dlpchilderrors;
extern trlEmuMenuAction cgbvcm_action_dlpchilderrors2dlpchilderror;

extern trlEmuMenuAction cgbvcm_action_dlperrorok_open;

extern trlEmuMenuAction cgbvcm_action_dlpreset_open;
extern trlEmuMenuAction cgbvcm_action_dlpreset_close;
extern trlEmuMenuAction cgbvcm_action_dlpreset_close1;

extern trlEmuMenuAction cgbvcm_action_dlpnreset_open;
extern trlEmuMenuAction cgbvcm_action_dlpnreset_close;
extern trlEmuMenuAction cgbvcm_action_dlpnreset_close1;

extern trlEmuMenuAction cgbvcm_action_dlpend_open;
extern trlEmuMenuAction cgbvcm_action_dlpend_close;
extern trlEmuMenuAction cgbvcm_action_dlpend_close1;

extern trlEmuMenuAction cgbvcm_action_dlpend2dlperror;
extern trlEmuMenuAction cgbvcm_action_dlpreset2dlperror;

extern trlEmuMenuAction cgbvcm_action_dlpnend_open;
extern trlEmuMenuAction cgbvcm_action_dlpnend_close;
extern trlEmuMenuAction cgbvcm_action_dlpnend_close1;

extern trlEmuMenuAction cgbvcm_action_dlpchildend_open;
extern trlEmuMenuAction cgbvcm_action_dlpchildendtochildendwait;
extern trlEmuMenuAction cgbvcm_action_dlpchildothermenutodlpchildendwait;
extern trlEmuMenuAction cgbvcm_action_dlpchildend2dlpchilderrors;
extern trlEmuMenuAction cgbvcm_action_dlpchildend2dlpchildothermenu;
extern trlEmuMenuAction cgbvcm_action_dlpchildend_close1;

extern trlEmuMenuAction cgbvcm_action_dlpendok_open;
extern trlEmuMenuAction cgbvcm_action_dlpendok_close;
extern trlEmuMenuAction cgbvcm_action_dlpendok2standby;
extern trlEmuMenuAction cgbvcm_action_dlpnendok2standby;
extern trlEmuMenuAction cgbvcm_action_dlpendwait_open;
extern trlEmuMenuAction cgbvcm_action_dlpendwait_close;
extern trlEmuMenuAction cgbvcm_action_dlpallleaveok_open;
extern trlEmuMenuAction cgbvcm_action_dlphaveerrorok_open;
extern trlEmuMenuAction cgbvcm_action_dlpallleaveok_open1;
extern trlEmuMenuAction cgbvcm_action_dlpallleaveok_close;
extern trlEmuMenuAction cgbvcm_action_dlphaveleaveok_open;
extern trlEmuMenuAction cgbvcm_action_dlphaveleaveok_open1;
extern trlEmuMenuAction cgbvcm_action_dlphaveleaveok_close;
extern trlEmuMenuAction cgbvcm_action_dlphaveleaveok_nclose;
extern trlEmuMenuAction cgbvcm_action_dlphaveerrorok_close;
extern trlEmuMenuAction cgbvcm_action_dlphaveleaveok_close1;

extern trlEmuMenuAction cgbvcm_action_netoppre2dlpdlperror;

extern trlEmuMenuAction cgbvcm_action_netconnconfirmopen;
extern trlEmuMenuAction cgbvcm_action_netconnconfirmback;
extern trlEmuMenuAction cgbvcm_action_netconnconfirm2netinit;
extern trlEmuMenuAction cgbvcm_action_netinit2dlpdlperror;
extern trlEmuMenuAction cgbvcm_action_netinit2dlpbegin;
extern trlEmuMenuAction cgbvcm_action_dlpdlperrorclose;
extern trlEmuMenuAction cgbvcm_action_dlperrorokclose;
extern trlEmuMenuAction cgbvcm_action_dlpnerrorokclose;
